#Insertion 
use company;
INSERT INTO role(role_name) VALUES
('Admin'),
('Editor'),
('Executive');

INSERT INTO designation(designation_name) VALUES
('Designation 1'),
('Designation 2'),
('Designation 3'),
('Designation 4'),
('Designation 5'),
('Designation 6'),
('Designation 7'),
('Designation 8'),
('Designation 9');


INSERT INTO department(department_name) VALUES
('Department 1'),
('Department 2'),
('Department 3'),
('Department 4'),
('Department 5'),
('Department 6');

INSERT INTO project(project_name) VALUES
('Project 1'),
('Project 2'),
('Project 3'),
('Project 4'),
('Project 5'),
('Project 6'),
('Project 7'),
('Project 8'),
('Project 9'),
('Project 10');

INSERT INTO location(location_name) VALUES
('Location 1'),
('Location 2'),
('Location 3'),
('Location 4'),
('Location 5'),
('Location 6'),
('Location 7'),
('Location 8'),
('Location 9'),
('Location 10');


	
INSERT INTO country (country_id, country_name) VALUES
(1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'Belarus'),
(5, 'Argentina'),
(6, 'Australia'),
(7, 'Azerbaijan'),
(8, 'Bahrain'),
(9, 'Bangladesh'),
(10, 'Barbados'),
(11, 'Belgium'),
(13, 'Botswana'),
(14, 'Brazil'),
(16, 'Congo'),
(17, 'Albania'),
(18, 'Cameroon'),
(19, 'Chad'),
(21, 'Chile'),
(22, 'China'),
(23, 'United Arab Emirates'),
(24, 'Colombia'),
(25, 'Congo'),
(26, 'Japan'),
(27, 'Cuba'),
(29, 'Denmark'),
(30, 'Egypt'),
(31, 'Eritrea'),
(32, 'Ethiopia'),
(33, 'Fiji'),
(34, 'Finland'),
(35, 'France'),
(36, 'Gambia'),
(37, 'Germany'),
(39, 'Greece'),
(40, 'Guinea'),
(41, 'Hong Kong'),
(42, 'Hungary'),
(43, 'Iceland'),
(44, 'India'),
(45, 'Indonesia'),
(46, 'Iran'),
(47, 'Iraq'),
(48, 'Ireland'),
(50, 'Italy'),
(51, 'Jamaica'),
(52, 'Japan'),
(53, 'Jordan'),
(54, 'Kazakhstan'),
(55, 'Kenya'),
(57, 'Kuwait'),
(58, 'Kyrgyzstan'),
(59, 'Lebanon'),
(60, 'Cyprus'),
(61, 'Madagascar'),
(62, 'Malawi'),
(63, 'Malaysia'),
(64, 'Mali'),
(65, 'Malta'),
(66, 'Mauritania'),
(67, 'Mauritius'),
(68, 'Mexico'),
(69, 'Morocco'),
(70, 'Mozambique'),
(71, 'Nepal'),
(72, 'Netherlands'),
(73, 'New Zealand'),
(74, 'Niger'),
(75, 'Nigeria'),
(76, 'Norway'),
(77, 'Oman'),
(78, 'Palestine'),
(79, 'Pakistan'),
(80, 'Peru'),
(81, 'Philippines'),
(82, 'Poland'),
(83, 'Portugal'),
(84, 'Qatar'),
(85, 'Russia'),
(86, 'Saudi Arabia'),
(87, 'Senegal'),
(88, 'Sierra Leone'),
(89, 'Singapore'),
(90, 'Slovenia'),
(91, 'Somalia'),
(92, 'South Africa'),
(94, 'Spain'),
(95, 'Sri Lanka'),
(96, 'Ghana'),
(97, 'Sweden'),
(98, 'Switzerland'),
(100, 'Tajikistan'),
(103, 'Thailand'),
(104, 'Tunisia'),
(105, 'Turkey'),
(106, 'Turkmenistan'),
(107, 'Uganda'),
(108, 'United Kingdom'),
(109, 'Uzbekistan'),
(110, 'Venezuela'),
(111, 'Yemen'),
(112, 'Zimbabwe'),
(113, 'Belize'),
(115, 'Austria'),
(116, 'Canada'),
(117, 'Laos'),
(118, 'Liberia'),
(119, 'Ukraine'),
(121, 'Rwanda'),
(122, 'Maldives'),
(128, 'Latvia'),
(142, 'Georgia'),
(158, 'Romania'),
(165, 'Slovakia'),
(173, 'Papua New Guinea'),
(187, 'Angola'),
(193, 'Bosnia'),
(196, 'Costa Rica'),
(217, 'Brussels'),
(219, 'South Korea'),
(220, 'Sudan'),
(222, 'Cambodia'),
(224, 'Serbia');